version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: shedlock-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shedlock_demo
      MYSQL_USER: shedlock_user
      MYSQL_PASSWORD: shedlock_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shedlock-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application Instance 1
  shedlock-app-1:
    build: .
    container_name: shedlock-app-1
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shedlock_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: shedlock_user
      SPRING_DATASOURCE_PASSWORD: shedlock_pass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shedlock-network
    restart: unless-stopped

  # Spring Boot Application Instance 2
  shedlock-app-2:
    build: .
    container_name: shedlock-app-2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shedlock_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: shedlock_user
      SPRING_DATASOURCE_PASSWORD: shedlock_pass
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shedlock-network
    restart: unless-stopped

  # Spring Boot Application Instance 3
  shedlock-app-3:
    build: .
    container_name: shedlock-app-3
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shedlock_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: shedlock_user
      SPRING_DATASOURCE_PASSWORD: shedlock_pass
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shedlock-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  shedlock-network:
    driver: bridge 