spring:
  application:
    name: shedlock-demo
  
  # MySQL Configuration for Docker
  datasource:
    url: jdbc:mysql://mysql:3306/shedlock_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:shedlock_user}
    password: ${SPRING_DATASOURCE_PASSWORD:shedlock_pass}
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        # Connection pool settings for Docker
        connection:
          provider_disables_autocommit: true
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# Logging Configuration
logging:
  level:
    com.example.shedlockdemo: INFO
    net.javacrumbs.shedlock: INFO
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# ShedLock Configuration
shedlock:
  defaults:
    lock-at-most-for: 30m
    lock-at-least-for: 1m

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 